backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "content"
    label: "Контент сайта"
    delete: false
    editor:
      preview: false
    files:
      - file: "portfolio.json"
        label: "Управление всеми разделами"
        name: "portfolio"
        fields:
          - {label: "Ваше Имя", name: "name", widget: "string"}
          - {label: "Профессия", name: "subtitle", widget: "string"}
          - {label: "Цвет фона (если нет картинки)", name: "bg_color", widget: "color"}
          - {label: "Фоновое изображение сайта", name: "bg_image", widget: "image", required: false}
          
          - {label: "Раздел: О нас (Текст)", name: "about", widget: "text"}
          
          - label: "Раздел: Видео"
            name: "videos"
            widget: "list"
            fields:
              - {label: "Название видео", name: "title", widget: "string"}
              - {label: "Описание", name: "description", widget: "text"}
              - {label: "Ссылка на видео (YouTube/Vimeo)", name: "video_url", widget: "string"}
              
          - label: "Раздел: Фото"
            name: "photos"
            widget: "list"
            fields:
              - {label: "Название фото", name: "title", widget: "string", required: false}
              - {label: "Загрузить Фотографию", name: "image", widget: "image"}
              
          - label: "Раздел: Проекты (Кейсы)"
            name: "projects"
            widget: "list"
            fields:
              - {label: "Название проекта", name: "title", widget: "string"}
              - {label: "Что было сделано (описание)", name: "description", widget: "text"}
              
          - {label: "Раздел: Оборудование (Техника)", name: "gear", widget: "text"}
          - {label: "Ссылка на Яндекс/Google Диск", name: "disk_link", widget: "string"}
