backend:
  name: git-gateway
  branch: main

media_folder: "images" # Сюда будут загружаться фотографии, если понадобятся
public_folder: "/images"

collections:
  - name: "pages"
    label: "Страницы"
    files:
      - file: "index.html"
        label: "Главная страница"
        name: "home"
        fields:
          - {label: "Ваше Имя", name: "title", widget: "string"}
          - {label: "Профессия", name: "subtitle", widget: "string"}
          - {label: "О себе", name: "bio", widget: "text"}
          - {label: "Ссылка на Яндекс/Google Диск", name: "disk_link", widget: "string"}